version: '3.1'

services:
  database:
    build:
      context: ./dev_infra/db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - '6379:6379'
volumes:
  postgres-data:
