version: "3.1"
services:
    embedding-service:
        build:
            context: ./embed-service
        ports:
            - 8000:8000
        environment:
            - DB_HOST=database
            - DB_USER=postgres
            - DB_PASSWORD=mypassword
            - DB_DATABASE=bot_builder
            - DB_PORT=5432
            - REDIS_HOST=redis
    chat-service:
        build:
            context: ./chat-service
        ports:
            - 5000:8000
        environment:
            - DB_HOST=database
            - DB_USER=postgres
            - DB_PASSWORD=mypassword
            - DB_DATABASE=bot_builder
            - DB_PORT=5432
            - REDIS_HOST=redis
