version: '3.1'

services:
  database:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - '6379:6379'
  embedding-service:
    build:
      context: ./botbuilder-embed-service
    ports:
      - 8000:8000
volumes:
  postgres-data:
