version: "3.1"
services:
    embedding-service:
        build:
            context: ./embed-service
        ports:
            - 8000:8000
    chat-service:
        build:
            context: ./chat-service
        ports:
            - 5000:8000
