version: "3"

services:
  chat-service:
    image: atulvinod1911/botbuilder-chat-service:latest
    ports:
      - 8000:8000
    deploy:
      replicas: 1
  embedding-service:
    image: atulvinod1911/botbuilder-embed-service:latest
    ports:
      - 5000:8000
    deploy:
      replicas: 1
    
