name: Build Containers

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Checkout Branch
              uses: actions/checkout@v3

            - name: Github Reference
              run: |
                echo "Ref: " -> ${{ github.ref }}

            - name: Login to Dockerhub
              uses: docker/login-action@v1
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_PASSWORD}}

            - name: Build Embedding Service
              uses: docker/build-push-action@v2
              with:
                context: './embed-service'
                file: 'Dockerfile'
                push: true
                tags: 'atulvinod1911/bot-builder-embed-service:${{github.ref}}'
                build-args: |
                    NEXT_PUBLIC_MAX_FILES_SIZE_LIMIT_MB=${{secrets.NEXT_PUBLIC_MAX_FILES_SIZE_LIMIT_MB}}
                    DB_HOST=${{secrets.DB_HOST}}
                    DB_USER=${{secrets.DB_USER}}
                    DB_PASSWORD=${{secrets.DB_PASSWORD}}
                    DB_DATABASE=${{secrets.DB_DATABASE}}
                    DB_PORT=${{secrets.DB_PORT}}
                    OPENAI_API_KEY=${{secrets.OPENAI_API_KEY}}
                    REDIS_HOST=${{secrets.REDIS_HOST}}
                    REDIS_PORT=${{secrets.REDIS_PORT}}
                    REDIS_USER=${{secrets.REDIS_USER}}
                    REDIS_PASSWORD=${{secrets.REDIS_PASSWORD}}
                    FIREBASE_API_KEY=${{secrets.FIREBASE_API_KEY}}
                    FIREBASE_AUTH_DOMAIN=${{secrets.FIREBASE_AUTH_DOMAIN}}
                    FIREBASE_PROJECT_ID=${{secrets.FIREBASE_PROJECT_ID}}
                    FIREBASE_STORAGE_BUCKET=${{secrets.FIREBASE_STORAGE_BUCKET}}
                    FIREBASE_MESSAGE_SENDER_ID=${{secrets.FIREBASE_MESSAGE_SENDER_ID}}
                    FIREBASE_APP_ID=${{secrets.FIREBASE_APP_ID}}
                    PINECONE_API_KEY=${{secrets.PINECONE_API_KEY}}


            - name: Build Chat Service
              uses: docker/build-push-action@v2
              with:
                context: './chat-service'
                file: 'Dockerfile'
                push: true
                tags: 'atulvinod1911/bot-builder-chat-service:${{github.ref}}'
                build-args: |
                    NEXT_PUBLIC_MAX_FILES_SIZE_LIMIT_MB=${{secrets.NEXT_PUBLIC_MAX_FILES_SIZE_LIMIT_MB}}
                    DB_HOST=${{secrets.DB_HOST}}
                    DB_USER=${{secrets.DB_USER}}
                    DB_PASSWORD=${{secrets.DB_PASSWORD}}
                    DB_DATABASE=${{secrets.DB_DATABASE}}
                    DB_PORT=${{secrets.DB_PORT}}
                    OPENAI_API_KEY=${{secrets.OPENAI_API_KEY}}
                    REDIS_HOST=${{secrets.REDIS_HOST}}
                    REDIS_PORT=${{secrets.REDIS_PORT}}
                    REDIS_USER=${{secrets.REDIS_USER}}
                    REDIS_PASSWORD=${{secrets.REDIS_PASSWORD}}
                    FIREBASE_API_KEY=${{secrets.FIREBASE_API_KEY}}
                    FIREBASE_AUTH_DOMAIN=${{secrets.FIREBASE_AUTH_DOMAIN}}
                    FIREBASE_PROJECT_ID=${{secrets.FIREBASE_PROJECT_ID}}
                    FIREBASE_STORAGE_BUCKET=${{secrets.FIREBASE_STORAGE_BUCKET}}
                    FIREBASE_MESSAGE_SENDER_ID=${{secrets.FIREBASE_MESSAGE_SENDER_ID}}
                    FIREBASE_APP_ID=${{secrets.FIREBASE_APP_ID}}
                    PINECONE_API_KEY=${{secrets.PINECONE_API_KEY}}

