name: Build Containers

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Checkout Branch
              uses: actions/checkout@v3

            - name: Github Reference
              run: |
                echo "Ref:  -> ${{ github.ref }}"

            - name: Login to Dockerhub
              uses: docker/login-action@v1
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_PASSWORD}}
            
            - name: Build Firebase Service Config
              uses: timheuer/base64-to-file@v1.2
              with:
                fileName: 'firebase_service_account_config.json'
                fileDir: './embed-service'
                encodedString: ${{secrets.FIREBASE_SERVICE_CONFIG}}

            - name: Build Embed service config
              uses: timheuer/base64-to-file@v1.2
              with:
                fileName: '.env'
                fileDir: './embed-service'
                encodedString: ${{secrets.EMBED_SERVICE_ENV}}
            
            - name: Build Chat service config
              uses: timheuer/base64-to-file@v1.2
              with:
                fileName: '.env'
                fileDir: './chat-service'
                encodedString: ${{secrets.CHAT_SERVICE_ENV}}


            - name: Docker Build Embedding Service
              uses: docker/build-push-action@v2
              with:
                context: './embed-service'
                file: 'Dockerfile'
                push: true
                tags: 'atulvinod1911/botbuilder-embed-service:latest'

            - name: Docker Build Chat Service
              uses: docker/build-push-action@v2
              with:
                context: './chat-service'
                file: 'Dockerfile'
                push: true
                tags: 'atulvinod1911/botbuilder-chat-service:latest'

