name: Build Containers

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Checkout Branch
              uses: actions/checkout@v3
              with:
                fetch-depth: 2

            - name: Github Reference
              run: |
                echo "Ref:  -> ${{ github.ref }}"

            - name: Get modified services
              run: |
                echo "Modified files"
                git diff --name-only HEAD^ HEAD
                echo "Paths of modified files"
                git diff --name-only HEAD^ HEAD &gt; files.txt
                
                run_upload_service=false
                run_chat_service=false
                run_embed_service=false

                while IFS= read -r file
                do
                  echo $file
                  if [[ $file == upload-service/* ]]; then
                    echo "Files modified in upload service"
                    run_upload_service=true
                  fi

                  if [[ $file == chat-service/* ]]; then
                    echo "Files modified in chat service"
                    run_chat_service=true
                  fi

                  if [[ $file == embed-service/* ]]; then
                    echo "Files modified in embed service"
                    run_embed_service=true
                  fi
                done &lt; files.txt
                              
                echo "::set-output name=run_upload_service::$run_upload_service"
                echo "::set-output name=run_chat_service::$run_chat_service"
                echo "::set-output name=run_embed_service::$run_embed_service"
                  
